/**
 * Generated by Scrooge
 *   version: 4.5.0
 *   rev: 014664de600267b36809bbc85225e26aec286216
 *   built at: 20160203-205352
 */
package com.jxjxgo.pc.rpc.domain

import com.twitter.finagle.Thrift
import com.twitter.finagle.stats.{NullStatsReceiver, StatsReceiver}
import com.twitter.scrooge.{ThriftStruct, TReusableMemoryTransport}
import com.twitter.util.{Future, Return, Throw, Throwables}
import java.nio.ByteBuffer
import java.util.Arrays
import org.apache.thrift.protocol._
import org.apache.thrift.TApplicationException
import org.apache.thrift.transport.TMemoryInputTransport
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, HashMap => mutable$HashMap}
import scala.collection.{Map, Set}

import scala.language.higherKinds


@javax.annotation.Generated(value = Array("com.twitter.scrooge.Compiler"))
class PCEndpoint$FinagleService(
  iface: PCEndpoint[Future],
  protocolFactory: TProtocolFactory,
  stats: StatsReceiver,
  maxThriftBufferSize: Int,
  serviceName: String
) extends com.twitter.finagle.Service[Array[Byte], Array[Byte]] {
  import PCEndpoint._

  def this(
    iface: PCEndpoint[Future],
    protocolFactory: TProtocolFactory,
    stats: StatsReceiver,
    maxThriftBufferSize: Int
  ) = this(iface, protocolFactory, stats, maxThriftBufferSize, "PCEndpoint")

  def this(
    iface: PCEndpoint[Future],
    protocolFactory: TProtocolFactory
  ) = this(iface, protocolFactory, NullStatsReceiver, Thrift.maxThriftBufferSize)

  private[this] val tlReusableBuffer = new ThreadLocal[TReusableMemoryTransport] {
    override def initialValue() = TReusableMemoryTransport(512)
  }

  private[this] def reusableBuffer: TReusableMemoryTransport = {
    val buf = tlReusableBuffer.get()
    buf.reset()
    buf
  }

  private[this] val resetCounter = stats.scope("buffer").counter("resetCount")

  private[this] def resetBuffer(trans: TReusableMemoryTransport): Unit = {
    if (trans.currentCapacity > maxThriftBufferSize) {
      resetCounter.incr()
      tlReusableBuffer.remove()
    }
  }

  protected val functionMap = new mutable$HashMap[String, (TProtocol, Int) => Future[Array[Byte]]]()

  protected def addFunction(name: String, f: (TProtocol, Int) => Future[Array[Byte]]) {
    functionMap(name) = f
  }

  protected def exception(name: String, seqid: Int, code: Int, message: String): Future[Array[Byte]] = {
    try {
      val x = new TApplicationException(code, message)
      val memoryBuffer = reusableBuffer
      try {
        val oprot = protocolFactory.getProtocol(memoryBuffer)

        oprot.writeMessageBegin(new TMessage(name, TMessageType.EXCEPTION, seqid))
        x.write(oprot)
        oprot.writeMessageEnd()
        oprot.getTransport().flush()
        Future.value(Arrays.copyOfRange(memoryBuffer.getArray(), 0, memoryBuffer.length()))
      } finally {
        resetBuffer(memoryBuffer)
      }
    } catch {
      case e: Exception => Future.exception(e)
    }
  }

  protected def reply(name: String, seqid: Int, result: ThriftStruct): Future[Array[Byte]] = {
    try {
      val memoryBuffer = reusableBuffer
      try {
        val oprot = protocolFactory.getProtocol(memoryBuffer)

        oprot.writeMessageBegin(new TMessage(name, TMessageType.REPLY, seqid))
        result.write(oprot)
        oprot.writeMessageEnd()

        Future.value(Arrays.copyOfRange(memoryBuffer.getArray(), 0, memoryBuffer.length()))
      } finally {
        resetBuffer(memoryBuffer)
      }
    } catch {
      case e: Exception => Future.exception(e)
    }
  }

  final def apply(request: Array[Byte]): Future[Array[Byte]] = {
    val inputTransport = new TMemoryInputTransport(request)
    val iprot = protocolFactory.getProtocol(inputTransport)

    try {
      val msg = iprot.readMessageBegin()
      val func = functionMap.get(msg.name)
      func match {
        case _root_.scala.Some(fn) =>
          fn(iprot, msg.seqid)
        case _ =>
          TProtocolUtil.skip(iprot, TType.STRUCT)
          exception(msg.name, msg.seqid, TApplicationException.UNKNOWN_METHOD,
            "Invalid method name: '" + msg.name + "'")
      }
    } catch {
      case e: Exception => Future.exception(e)
    }
  }

  // ---- end boilerplate.

  private[this] val scopedStats = if (serviceName != "") stats.scope(serviceName) else stats
  private[this] object __stats_sign {
    val RequestsCounter = scopedStats.scope("sign").counter("requests")
    val SuccessCounter = scopedStats.scope("sign").counter("success")
    val FailuresCounter = scopedStats.scope("sign").counter("failures")
    val FailuresScope = scopedStats.scope("sign").scope("failures")
  }
  addFunction("sign", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_sign.RequestsCounter.incr()
      val args = Sign.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.sign(args.traceId, args.request)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: com.jxjxgo.pc.rpc.domain.SignResponse =>
        reply("sign", seqid, Sign.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_sign.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_sign.FailuresCounter.incr()
          __stats_sign.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("sign", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_callback {
    val RequestsCounter = scopedStats.scope("callback").counter("requests")
    val SuccessCounter = scopedStats.scope("callback").counter("success")
    val FailuresCounter = scopedStats.scope("callback").counter("failures")
    val FailuresScope = scopedStats.scope("callback").scope("failures")
  }
  addFunction("callback", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_callback.RequestsCounter.incr()
      val args = Callback.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.callback(args.traceId, args.request)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: com.jxjxgo.pc.rpc.domain.CallbackResponse =>
        reply("callback", seqid, Callback.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_callback.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_callback.FailuresCounter.incr()
          __stats_callback.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("callback", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_query {
    val RequestsCounter = scopedStats.scope("query").counter("requests")
    val SuccessCounter = scopedStats.scope("query").counter("success")
    val FailuresCounter = scopedStats.scope("query").counter("failures")
    val FailuresScope = scopedStats.scope("query").scope("failures")
  }
  addFunction("query", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_query.RequestsCounter.incr()
      val args = Query.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.query(args.traceId, args.request)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: com.jxjxgo.pc.rpc.domain.QueryResponse =>
        reply("query", seqid, Query.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_query.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_query.FailuresCounter.incr()
          __stats_query.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("query", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_download {
    val RequestsCounter = scopedStats.scope("download").counter("requests")
    val SuccessCounter = scopedStats.scope("download").counter("success")
    val FailuresCounter = scopedStats.scope("download").counter("failures")
    val FailuresScope = scopedStats.scope("download").scope("failures")
  }
  addFunction("download", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_download.RequestsCounter.incr()
      val args = Download.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.download(args.traceId, args.request)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: com.jxjxgo.pc.rpc.domain.DownloadWaterRecordsResponse =>
        reply("download", seqid, Download.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_download.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_download.FailuresCounter.incr()
          __stats_download.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("download", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
}