/**
 * Generated by Scrooge
 *   version: 4.5.0
 *   rev: 014664de600267b36809bbc85225e26aec286216
 *   built at: 20160203-205352
 */
package com.jxjxgo.pc.rpc.domain

import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob, ThriftException, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo,
  ThriftStructMetaData, ThriftUtil}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import java.util.Arrays
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object QueryResponse extends ThriftStructCodec3[QueryResponse] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("QueryResponse")
  val CodeField = new TField("code", TType.STRING, 1)
  val CodeFieldManifest = implicitly[Manifest[String]]
  val PaymentVoucherNoField = new TField("paymentVoucherNo", TType.STRING, 2)
  val PaymentVoucherNoFieldManifest = implicitly[Manifest[String]]
  val AmountField = new TField("amount", TType.STRING, 3)
  val AmountFieldManifest = implicitly[Manifest[String]]
  val ChannelCodeField = new TField("channelCode", TType.STRING, 4)
  val ChannelCodeFieldManifest = implicitly[Manifest[String]]
  val ApiResultCodeField = new TField("apiResultCode", TType.STRING, 5)
  val ApiResultCodeFieldManifest = implicitly[Manifest[String]]
  val ExtOrderNoField = new TField("extOrderNo", TType.STRING, 6)
  val ExtOrderNoFieldManifest = implicitly[Manifest[String]]
  val ExtWaterNoField = new TField("extWaterNo", TType.STRING, 7)
  val ExtWaterNoFieldManifest = implicitly[Manifest[String]]
  val Ext1Field = new TField("ext1", TType.STRING, 8)
  val Ext1FieldManifest = implicitly[Manifest[String]]
  val Ext2Field = new TField("ext2", TType.STRING, 9)
  val Ext2FieldManifest = implicitly[Manifest[String]]
  val Ext3Field = new TField("ext3", TType.STRING, 10)
  val Ext3FieldManifest = implicitly[Manifest[String]]
  val Ext4Field = new TField("ext4", TType.STRING, 11)
  val Ext4FieldManifest = implicitly[Manifest[String]]
  val Ext5Field = new TField("ext5", TType.STRING, 12)
  val Ext5FieldManifest = implicitly[Manifest[String]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      CodeField,
      false,
      false,
      CodeFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      PaymentVoucherNoField,
      false,
      false,
      PaymentVoucherNoFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      AmountField,
      false,
      false,
      AmountFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      ChannelCodeField,
      false,
      false,
      ChannelCodeFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      ApiResultCodeField,
      false,
      false,
      ApiResultCodeFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      ExtOrderNoField,
      false,
      false,
      ExtOrderNoFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      ExtWaterNoField,
      false,
      false,
      ExtWaterNoFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      Ext1Field,
      false,
      false,
      Ext1FieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      Ext2Field,
      false,
      false,
      Ext2FieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      Ext3Field,
      false,
      false,
      Ext3FieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      Ext4Field,
      false,
      false,
      Ext4FieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      Ext5Field,
      false,
      false,
      Ext5FieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: QueryResponse): Unit = {
  }

  def withoutPassthroughFields(original: QueryResponse): QueryResponse =
    new Immutable(
      code =
        {
          val field = original.code
          field
        },
      paymentVoucherNo =
        {
          val field = original.paymentVoucherNo
          field
        },
      amount =
        {
          val field = original.amount
          field
        },
      channelCode =
        {
          val field = original.channelCode
          field
        },
      apiResultCode =
        {
          val field = original.apiResultCode
          field
        },
      extOrderNo =
        {
          val field = original.extOrderNo
          field
        },
      extWaterNo =
        {
          val field = original.extWaterNo
          field
        },
      ext1 =
        {
          val field = original.ext1
          field
        },
      ext2 =
        {
          val field = original.ext2
          field
        },
      ext3 =
        {
          val field = original.ext3
          field
        },
      ext4 =
        {
          val field = original.ext4
          field
        },
      ext5 =
        {
          val field = original.ext5
          field
        }
    )

  override def encode(_item: QueryResponse, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }

  private[this] def lazyDecode(_iprot: LazyTProtocol): QueryResponse = {

    var codeOffset: Int = -1
    var paymentVoucherNoOffset: Int = -1
    var amountOffset: Int = -1
    var channelCodeOffset: Int = -1
    var apiResultCodeOffset: Int = -1
    var extOrderNoOffset: Int = -1
    var extWaterNoOffset: Int = -1
    var ext1Offset: Int = -1
    var ext2Offset: Int = -1
    var ext3Offset: Int = -1
    var ext4Offset: Int = -1
    var ext5Offset: Int = -1

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRING =>
                codeOffset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'code' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRING =>
                paymentVoucherNoOffset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'paymentVoucherNo' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.STRING =>
                amountOffset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'amount' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 4 =>
            _field.`type` match {
              case TType.STRING =>
                channelCodeOffset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'channelCode' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 5 =>
            _field.`type` match {
              case TType.STRING =>
                apiResultCodeOffset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'apiResultCode' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 6 =>
            _field.`type` match {
              case TType.STRING =>
                extOrderNoOffset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'extOrderNo' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 7 =>
            _field.`type` match {
              case TType.STRING =>
                extWaterNoOffset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'extWaterNo' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 8 =>
            _field.`type` match {
              case TType.STRING =>
                ext1Offset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'ext1' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 9 =>
            _field.`type` match {
              case TType.STRING =>
                ext2Offset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'ext2' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 10 =>
            _field.`type` match {
              case TType.STRING =>
                ext3Offset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'ext3' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 11 =>
            _field.`type` match {
              case TType.STRING =>
                ext4Offset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'ext4' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 12 =>
            _field.`type` match {
              case TType.STRING =>
                ext5Offset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'ext5' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      codeOffset,
      paymentVoucherNoOffset,
      amountOffset,
      channelCodeOffset,
      apiResultCodeOffset,
      extOrderNoOffset,
      extWaterNoOffset,
      ext1Offset,
      ext2Offset,
      ext3Offset,
      ext4Offset,
      ext5Offset,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): QueryResponse =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[this] def eagerDecode(_iprot: TProtocol): QueryResponse = {
    var code: String = ""
    var paymentVoucherNo: String = ""
    var amount: String = ""
    var channelCode: String = ""
    var apiResultCode: String = ""
    var extOrderNo: String = ""
    var extWaterNo: String = ""
    var ext1: String = ""
    var ext2: String = ""
    var ext3: String = ""
    var ext4: String = ""
    var ext5: String = ""
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRING =>
                code = readCodeValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'code' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRING =>
                paymentVoucherNo = readPaymentVoucherNoValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'paymentVoucherNo' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.STRING =>
                amount = readAmountValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'amount' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 4 =>
            _field.`type` match {
              case TType.STRING =>
                channelCode = readChannelCodeValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'channelCode' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 5 =>
            _field.`type` match {
              case TType.STRING =>
                apiResultCode = readApiResultCodeValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'apiResultCode' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 6 =>
            _field.`type` match {
              case TType.STRING =>
                extOrderNo = readExtOrderNoValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'extOrderNo' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 7 =>
            _field.`type` match {
              case TType.STRING =>
                extWaterNo = readExtWaterNoValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'extWaterNo' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 8 =>
            _field.`type` match {
              case TType.STRING =>
                ext1 = readExt1Value(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'ext1' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 9 =>
            _field.`type` match {
              case TType.STRING =>
                ext2 = readExt2Value(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'ext2' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 10 =>
            _field.`type` match {
              case TType.STRING =>
                ext3 = readExt3Value(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'ext3' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 11 =>
            _field.`type` match {
              case TType.STRING =>
                ext4 = readExt4Value(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'ext4' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 12 =>
            _field.`type` match {
              case TType.STRING =>
                ext5 = readExt5Value(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'ext5' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new Immutable(
      code,
      paymentVoucherNo,
      amount,
      channelCode,
      apiResultCode,
      extOrderNo,
      extWaterNo,
      ext1,
      ext2,
      ext3,
      ext4,
      ext5,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    code: String = "",
    paymentVoucherNo: String = "",
    amount: String = "",
    channelCode: String = "",
    apiResultCode: String = "",
    extOrderNo: String = "",
    extWaterNo: String = "",
    ext1: String = "",
    ext2: String = "",
    ext3: String = "",
    ext4: String = "",
    ext5: String = ""
  ): QueryResponse =
    new Immutable(
      code,
      paymentVoucherNo,
      amount,
      channelCode,
      apiResultCode,
      extOrderNo,
      extWaterNo,
      ext1,
      ext2,
      ext3,
      ext4,
      ext5
    )

  def unapply(_item: QueryResponse): _root_.scala.Option[scala.Product12[String, String, String, String, String, String, String, String, String, String, String, String]] = _root_.scala.Some(_item)


  @inline private def readCodeValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeCodeField(code_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(CodeField)
    writeCodeValue(code_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeCodeValue(code_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(code_item)
  }

  @inline private def readPaymentVoucherNoValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writePaymentVoucherNoField(paymentVoucherNo_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(PaymentVoucherNoField)
    writePaymentVoucherNoValue(paymentVoucherNo_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writePaymentVoucherNoValue(paymentVoucherNo_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(paymentVoucherNo_item)
  }

  @inline private def readAmountValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeAmountField(amount_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(AmountField)
    writeAmountValue(amount_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeAmountValue(amount_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(amount_item)
  }

  @inline private def readChannelCodeValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeChannelCodeField(channelCode_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(ChannelCodeField)
    writeChannelCodeValue(channelCode_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeChannelCodeValue(channelCode_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(channelCode_item)
  }

  @inline private def readApiResultCodeValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeApiResultCodeField(apiResultCode_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(ApiResultCodeField)
    writeApiResultCodeValue(apiResultCode_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeApiResultCodeValue(apiResultCode_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(apiResultCode_item)
  }

  @inline private def readExtOrderNoValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeExtOrderNoField(extOrderNo_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(ExtOrderNoField)
    writeExtOrderNoValue(extOrderNo_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeExtOrderNoValue(extOrderNo_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(extOrderNo_item)
  }

  @inline private def readExtWaterNoValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeExtWaterNoField(extWaterNo_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(ExtWaterNoField)
    writeExtWaterNoValue(extWaterNo_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeExtWaterNoValue(extWaterNo_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(extWaterNo_item)
  }

  @inline private def readExt1Value(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeExt1Field(ext1_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(Ext1Field)
    writeExt1Value(ext1_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeExt1Value(ext1_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(ext1_item)
  }

  @inline private def readExt2Value(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeExt2Field(ext2_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(Ext2Field)
    writeExt2Value(ext2_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeExt2Value(ext2_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(ext2_item)
  }

  @inline private def readExt3Value(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeExt3Field(ext3_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(Ext3Field)
    writeExt3Value(ext3_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeExt3Value(ext3_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(ext3_item)
  }

  @inline private def readExt4Value(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeExt4Field(ext4_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(Ext4Field)
    writeExt4Value(ext4_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeExt4Value(ext4_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(ext4_item)
  }

  @inline private def readExt5Value(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeExt5Field(ext5_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(Ext5Field)
    writeExt5Value(ext5_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeExt5Value(ext5_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(ext5_item)
  }


  object Immutable extends ThriftStructCodec3[QueryResponse] {
    override def encode(_item: QueryResponse, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): QueryResponse = QueryResponse.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[QueryResponse] = QueryResponse.metaData
  }

  /**
   * The default read-only implementation of QueryResponse.  You typically should not need to
   * directly reference this class; instead, use the QueryResponse.apply method to construct
   * new instances.
   */
  class Immutable(
      val code: String,
      val paymentVoucherNo: String,
      val amount: String,
      val channelCode: String,
      val apiResultCode: String,
      val extOrderNo: String,
      val extWaterNo: String,
      val ext1: String,
      val ext2: String,
      val ext3: String,
      val ext4: String,
      val ext5: String,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends QueryResponse {
    def this(
      code: String = "",
      paymentVoucherNo: String = "",
      amount: String = "",
      channelCode: String = "",
      apiResultCode: String = "",
      extOrderNo: String = "",
      extWaterNo: String = "",
      ext1: String = "",
      ext2: String = "",
      ext3: String = "",
      ext4: String = "",
      ext5: String = ""
    ) = this(
      code,
      paymentVoucherNo,
      amount,
      channelCode,
      apiResultCode,
      extOrderNo,
      extWaterNo,
      ext1,
      ext2,
      ext3,
      ext4,
      ext5,
      Map.empty
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      codeOffset: Int,
      paymentVoucherNoOffset: Int,
      amountOffset: Int,
      channelCodeOffset: Int,
      apiResultCodeOffset: Int,
      extOrderNoOffset: Int,
      extWaterNoOffset: Int,
      ext1Offset: Int,
      ext2Offset: Int,
      ext3Offset: Int,
      ext4Offset: Int,
      ext5Offset: Int,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends QueryResponse {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }

    lazy val code: String =
      if (codeOffset == -1)
        ""
      else {
        _proto.decodeString(_buf, codeOffset)
      }
    lazy val paymentVoucherNo: String =
      if (paymentVoucherNoOffset == -1)
        ""
      else {
        _proto.decodeString(_buf, paymentVoucherNoOffset)
      }
    lazy val amount: String =
      if (amountOffset == -1)
        ""
      else {
        _proto.decodeString(_buf, amountOffset)
      }
    lazy val channelCode: String =
      if (channelCodeOffset == -1)
        ""
      else {
        _proto.decodeString(_buf, channelCodeOffset)
      }
    lazy val apiResultCode: String =
      if (apiResultCodeOffset == -1)
        ""
      else {
        _proto.decodeString(_buf, apiResultCodeOffset)
      }
    lazy val extOrderNo: String =
      if (extOrderNoOffset == -1)
        ""
      else {
        _proto.decodeString(_buf, extOrderNoOffset)
      }
    lazy val extWaterNo: String =
      if (extWaterNoOffset == -1)
        ""
      else {
        _proto.decodeString(_buf, extWaterNoOffset)
      }
    lazy val ext1: String =
      if (ext1Offset == -1)
        ""
      else {
        _proto.decodeString(_buf, ext1Offset)
      }
    lazy val ext2: String =
      if (ext2Offset == -1)
        ""
      else {
        _proto.decodeString(_buf, ext2Offset)
      }
    lazy val ext3: String =
      if (ext3Offset == -1)
        ""
      else {
        _proto.decodeString(_buf, ext3Offset)
      }
    lazy val ext4: String =
      if (ext4Offset == -1)
        ""
      else {
        _proto.decodeString(_buf, ext4Offset)
      }
    lazy val ext5: String =
      if (ext5Offset == -1)
        ""
      else {
        _proto.decodeString(_buf, ext5Offset)
      }

    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the QueryResponse trait with additional state or
   * behavior and implement the read-only methods from QueryResponse using an underlying
   * instance.
   */
  trait Proxy extends QueryResponse {
    protected def _underlying_QueryResponse: QueryResponse
    override def code: String = _underlying_QueryResponse.code
    override def paymentVoucherNo: String = _underlying_QueryResponse.paymentVoucherNo
    override def amount: String = _underlying_QueryResponse.amount
    override def channelCode: String = _underlying_QueryResponse.channelCode
    override def apiResultCode: String = _underlying_QueryResponse.apiResultCode
    override def extOrderNo: String = _underlying_QueryResponse.extOrderNo
    override def extWaterNo: String = _underlying_QueryResponse.extWaterNo
    override def ext1: String = _underlying_QueryResponse.ext1
    override def ext2: String = _underlying_QueryResponse.ext2
    override def ext3: String = _underlying_QueryResponse.ext3
    override def ext4: String = _underlying_QueryResponse.ext4
    override def ext5: String = _underlying_QueryResponse.ext5
    override def _passthroughFields = _underlying_QueryResponse._passthroughFields
  }
}

trait QueryResponse
  extends ThriftStruct
  with scala.Product12[String, String, String, String, String, String, String, String, String, String, String, String]
  with java.io.Serializable
{
  import QueryResponse._

  def code: String
  def paymentVoucherNo: String
  def amount: String
  def channelCode: String
  def apiResultCode: String
  def extOrderNo: String
  def extWaterNo: String
  def ext1: String
  def ext2: String
  def ext3: String
  def ext4: String
  def ext5: String

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = code
  def _2 = paymentVoucherNo
  def _3 = amount
  def _4 = channelCode
  def _5 = apiResultCode
  def _6 = extOrderNo
  def _7 = extWaterNo
  def _8 = ext1
  def _9 = ext2
  def _10 = ext3
  def _11 = ext4
  def _12 = ext5


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (code ne null) {
                writeCodeValue(code, _oprot)
                _root_.scala.Some(QueryResponse.CodeField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (paymentVoucherNo ne null) {
                writePaymentVoucherNoValue(paymentVoucherNo, _oprot)
                _root_.scala.Some(QueryResponse.PaymentVoucherNoField)
              } else {
                _root_.scala.None
              }
            case 3 =>
              if (amount ne null) {
                writeAmountValue(amount, _oprot)
                _root_.scala.Some(QueryResponse.AmountField)
              } else {
                _root_.scala.None
              }
            case 4 =>
              if (channelCode ne null) {
                writeChannelCodeValue(channelCode, _oprot)
                _root_.scala.Some(QueryResponse.ChannelCodeField)
              } else {
                _root_.scala.None
              }
            case 5 =>
              if (apiResultCode ne null) {
                writeApiResultCodeValue(apiResultCode, _oprot)
                _root_.scala.Some(QueryResponse.ApiResultCodeField)
              } else {
                _root_.scala.None
              }
            case 6 =>
              if (extOrderNo ne null) {
                writeExtOrderNoValue(extOrderNo, _oprot)
                _root_.scala.Some(QueryResponse.ExtOrderNoField)
              } else {
                _root_.scala.None
              }
            case 7 =>
              if (extWaterNo ne null) {
                writeExtWaterNoValue(extWaterNo, _oprot)
                _root_.scala.Some(QueryResponse.ExtWaterNoField)
              } else {
                _root_.scala.None
              }
            case 8 =>
              if (ext1 ne null) {
                writeExt1Value(ext1, _oprot)
                _root_.scala.Some(QueryResponse.Ext1Field)
              } else {
                _root_.scala.None
              }
            case 9 =>
              if (ext2 ne null) {
                writeExt2Value(ext2, _oprot)
                _root_.scala.Some(QueryResponse.Ext2Field)
              } else {
                _root_.scala.None
              }
            case 10 =>
              if (ext3 ne null) {
                writeExt3Value(ext3, _oprot)
                _root_.scala.Some(QueryResponse.Ext3Field)
              } else {
                _root_.scala.None
              }
            case 11 =>
              if (ext4 ne null) {
                writeExt4Value(ext4, _oprot)
                _root_.scala.Some(QueryResponse.Ext4Field)
              } else {
                _root_.scala.None
              }
            case 12 =>
              if (ext5 ne null) {
                writeExt5Value(ext5, _oprot)
                _root_.scala.Some(QueryResponse.Ext5Field)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
            _root_.scala.Some(TFieldBlob(_field, _data))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): QueryResponse = {
    var code: String = this.code
    var paymentVoucherNo: String = this.paymentVoucherNo
    var amount: String = this.amount
    var channelCode: String = this.channelCode
    var apiResultCode: String = this.apiResultCode
    var extOrderNo: String = this.extOrderNo
    var extWaterNo: String = this.extWaterNo
    var ext1: String = this.ext1
    var ext2: String = this.ext2
    var ext3: String = this.ext3
    var ext4: String = this.ext4
    var ext5: String = this.ext5
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        code = readCodeValue(_blob.read)
      case 2 =>
        paymentVoucherNo = readPaymentVoucherNoValue(_blob.read)
      case 3 =>
        amount = readAmountValue(_blob.read)
      case 4 =>
        channelCode = readChannelCodeValue(_blob.read)
      case 5 =>
        apiResultCode = readApiResultCodeValue(_blob.read)
      case 6 =>
        extOrderNo = readExtOrderNoValue(_blob.read)
      case 7 =>
        extWaterNo = readExtWaterNoValue(_blob.read)
      case 8 =>
        ext1 = readExt1Value(_blob.read)
      case 9 =>
        ext2 = readExt2Value(_blob.read)
      case 10 =>
        ext3 = readExt3Value(_blob.read)
      case 11 =>
        ext4 = readExt4Value(_blob.read)
      case 12 =>
        ext5 = readExt5Value(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      code,
      paymentVoucherNo,
      amount,
      channelCode,
      apiResultCode,
      extOrderNo,
      extWaterNo,
      ext1,
      ext2,
      ext3,
      ext4,
      ext5,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): QueryResponse = {
    var code: String = this.code
    var paymentVoucherNo: String = this.paymentVoucherNo
    var amount: String = this.amount
    var channelCode: String = this.channelCode
    var apiResultCode: String = this.apiResultCode
    var extOrderNo: String = this.extOrderNo
    var extWaterNo: String = this.extWaterNo
    var ext1: String = this.ext1
    var ext2: String = this.ext2
    var ext3: String = this.ext3
    var ext4: String = this.ext4
    var ext5: String = this.ext5

    _fieldId match {
      case 1 =>
        code = ""
      case 2 =>
        paymentVoucherNo = ""
      case 3 =>
        amount = ""
      case 4 =>
        channelCode = ""
      case 5 =>
        apiResultCode = ""
      case 6 =>
        extOrderNo = ""
      case 7 =>
        extWaterNo = ""
      case 8 =>
        ext1 = ""
      case 9 =>
        ext2 = ""
      case 10 =>
        ext3 = ""
      case 11 =>
        ext4 = ""
      case 12 =>
        ext5 = ""
      case _ =>
    }
    new Immutable(
      code,
      paymentVoucherNo,
      amount,
      channelCode,
      apiResultCode,
      extOrderNo,
      extWaterNo,
      ext1,
      ext2,
      ext3,
      ext4,
      ext5,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetCode: QueryResponse = unsetField(1)

  def unsetPaymentVoucherNo: QueryResponse = unsetField(2)

  def unsetAmount: QueryResponse = unsetField(3)

  def unsetChannelCode: QueryResponse = unsetField(4)

  def unsetApiResultCode: QueryResponse = unsetField(5)

  def unsetExtOrderNo: QueryResponse = unsetField(6)

  def unsetExtWaterNo: QueryResponse = unsetField(7)

  def unsetExt1: QueryResponse = unsetField(8)

  def unsetExt2: QueryResponse = unsetField(9)

  def unsetExt3: QueryResponse = unsetField(10)

  def unsetExt4: QueryResponse = unsetField(11)

  def unsetExt5: QueryResponse = unsetField(12)


  override def write(_oprot: TProtocol): Unit = {
    QueryResponse.validate(this)
    _oprot.writeStructBegin(Struct)
    if (code ne null) writeCodeField(code, _oprot)
    if (paymentVoucherNo ne null) writePaymentVoucherNoField(paymentVoucherNo, _oprot)
    if (amount ne null) writeAmountField(amount, _oprot)
    if (channelCode ne null) writeChannelCodeField(channelCode, _oprot)
    if (apiResultCode ne null) writeApiResultCodeField(apiResultCode, _oprot)
    if (extOrderNo ne null) writeExtOrderNoField(extOrderNo, _oprot)
    if (extWaterNo ne null) writeExtWaterNoField(extWaterNo, _oprot)
    if (ext1 ne null) writeExt1Field(ext1, _oprot)
    if (ext2 ne null) writeExt2Field(ext2, _oprot)
    if (ext3 ne null) writeExt3Field(ext3, _oprot)
    if (ext4 ne null) writeExt4Field(ext4, _oprot)
    if (ext5 ne null) writeExt5Field(ext5, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    code: String = this.code,
    paymentVoucherNo: String = this.paymentVoucherNo,
    amount: String = this.amount,
    channelCode: String = this.channelCode,
    apiResultCode: String = this.apiResultCode,
    extOrderNo: String = this.extOrderNo,
    extWaterNo: String = this.extWaterNo,
    ext1: String = this.ext1,
    ext2: String = this.ext2,
    ext3: String = this.ext3,
    ext4: String = this.ext4,
    ext5: String = this.ext5,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): QueryResponse =
    new Immutable(
      code,
      paymentVoucherNo,
      amount,
      channelCode,
      apiResultCode,
      extOrderNo,
      extWaterNo,
      ext1,
      ext2,
      ext3,
      ext4,
      ext5,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[QueryResponse]

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[QueryResponse]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 12

  override def productElement(n: Int): Any = n match {
    case 0 => this.code
    case 1 => this.paymentVoucherNo
    case 2 => this.amount
    case 3 => this.channelCode
    case 4 => this.apiResultCode
    case 5 => this.extOrderNo
    case 6 => this.extWaterNo
    case 7 => this.ext1
    case 8 => this.ext2
    case 9 => this.ext3
    case 10 => this.ext4
    case 11 => this.ext5
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "QueryResponse"
}