// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `pc.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcPC;

public interface _PCEndpointOperations
{
    SignResponse sign(String traceId, SignRequest request, Ice.Current __current);

    CallbackResponse callback(String traceId, CallbackRequest request, Ice.Current __current);

    QueryResponse query(String traceId, QueryRequest request, Ice.Current __current);

    DownloadWaterRecordsResponse download(String traceId, DownloadWaterRecordsRequest request, Ice.Current __current);
}
