// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `pc.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcPC;

public interface PCEndpoint extends Ice.Object,
                                    _PCEndpointOperations, _PCEndpointOperationsNC
{
    public static final String ice_staticId = "::RpcPC::PCEndpoint";

    public static final long serialVersionUID = -6768574089462818785L;
}
