// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `pc.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcPC;

public interface PCEndpointPrx extends Ice.ObjectPrx
{
    public SignResponse sign(String traceId, SignRequest request);

    public SignResponse sign(String traceId, SignRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sign(String traceId, SignRequest request);

    public Ice.AsyncResult begin_sign(String traceId, SignRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sign(String traceId, SignRequest request, Ice.Callback __cb);

    public Ice.AsyncResult begin_sign(String traceId, SignRequest request, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sign(String traceId, SignRequest request, Callback_PCEndpoint_sign __cb);

    public Ice.AsyncResult begin_sign(String traceId, SignRequest request, java.util.Map<String, String> __ctx, Callback_PCEndpoint_sign __cb);

    public Ice.AsyncResult begin_sign(String traceId,
                                      SignRequest request,
                                      IceInternal.Functional_GenericCallback1<SignResponse> __responseCb,
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sign(String traceId,
                                      SignRequest request,
                                      IceInternal.Functional_GenericCallback1<SignResponse> __responseCb,
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                      IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_sign(String traceId,
                                      SignRequest request,
                                      java.util.Map<String, String> __ctx,
                                      IceInternal.Functional_GenericCallback1<SignResponse> __responseCb,
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sign(String traceId,
                                      SignRequest request,
                                      java.util.Map<String, String> __ctx,
                                      IceInternal.Functional_GenericCallback1<SignResponse> __responseCb,
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                      IceInternal.Functional_BoolCallback __sentCb);

    public SignResponse end_sign(Ice.AsyncResult __result);

    public CallbackResponse callback(String traceId, CallbackRequest request);

    public CallbackResponse callback(String traceId, CallbackRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_callback(String traceId, CallbackRequest request);

    public Ice.AsyncResult begin_callback(String traceId, CallbackRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_callback(String traceId, CallbackRequest request, Ice.Callback __cb);

    public Ice.AsyncResult begin_callback(String traceId, CallbackRequest request, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_callback(String traceId, CallbackRequest request, Callback_PCEndpoint_callback __cb);

    public Ice.AsyncResult begin_callback(String traceId, CallbackRequest request, java.util.Map<String, String> __ctx, Callback_PCEndpoint_callback __cb);

    public Ice.AsyncResult begin_callback(String traceId,
                                          CallbackRequest request,
                                          IceInternal.Functional_GenericCallback1<CallbackResponse> __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_callback(String traceId,
                                          CallbackRequest request,
                                          IceInternal.Functional_GenericCallback1<CallbackResponse> __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_callback(String traceId,
                                          CallbackRequest request,
                                          java.util.Map<String, String> __ctx,
                                          IceInternal.Functional_GenericCallback1<CallbackResponse> __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_callback(String traceId,
                                          CallbackRequest request,
                                          java.util.Map<String, String> __ctx,
                                          IceInternal.Functional_GenericCallback1<CallbackResponse> __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                          IceInternal.Functional_BoolCallback __sentCb);

    public CallbackResponse end_callback(Ice.AsyncResult __result);

    public QueryResponse query(String traceId, QueryRequest request);

    public QueryResponse query(String traceId, QueryRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_query(String traceId, QueryRequest request);

    public Ice.AsyncResult begin_query(String traceId, QueryRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_query(String traceId, QueryRequest request, Ice.Callback __cb);

    public Ice.AsyncResult begin_query(String traceId, QueryRequest request, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_query(String traceId, QueryRequest request, Callback_PCEndpoint_query __cb);

    public Ice.AsyncResult begin_query(String traceId, QueryRequest request, java.util.Map<String, String> __ctx, Callback_PCEndpoint_query __cb);

    public Ice.AsyncResult begin_query(String traceId,
                                       QueryRequest request,
                                       IceInternal.Functional_GenericCallback1<QueryResponse> __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_query(String traceId,
                                       QueryRequest request,
                                       IceInternal.Functional_GenericCallback1<QueryResponse> __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_query(String traceId,
                                       QueryRequest request,
                                       java.util.Map<String, String> __ctx,
                                       IceInternal.Functional_GenericCallback1<QueryResponse> __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_query(String traceId,
                                       QueryRequest request,
                                       java.util.Map<String, String> __ctx,
                                       IceInternal.Functional_GenericCallback1<QueryResponse> __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                       IceInternal.Functional_BoolCallback __sentCb);

    public QueryResponse end_query(Ice.AsyncResult __result);

    public DownloadWaterRecordsResponse download(String traceId, DownloadWaterRecordsRequest request);

    public DownloadWaterRecordsResponse download(String traceId, DownloadWaterRecordsRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_download(String traceId, DownloadWaterRecordsRequest request);

    public Ice.AsyncResult begin_download(String traceId, DownloadWaterRecordsRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_download(String traceId, DownloadWaterRecordsRequest request, Ice.Callback __cb);

    public Ice.AsyncResult begin_download(String traceId, DownloadWaterRecordsRequest request, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_download(String traceId, DownloadWaterRecordsRequest request, Callback_PCEndpoint_download __cb);

    public Ice.AsyncResult begin_download(String traceId, DownloadWaterRecordsRequest request, java.util.Map<String, String> __ctx, Callback_PCEndpoint_download __cb);

    public Ice.AsyncResult begin_download(String traceId,
                                          DownloadWaterRecordsRequest request,
                                          IceInternal.Functional_GenericCallback1<DownloadWaterRecordsResponse> __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_download(String traceId,
                                          DownloadWaterRecordsRequest request,
                                          IceInternal.Functional_GenericCallback1<DownloadWaterRecordsResponse> __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_download(String traceId,
                                          DownloadWaterRecordsRequest request,
                                          java.util.Map<String, String> __ctx,
                                          IceInternal.Functional_GenericCallback1<DownloadWaterRecordsResponse> __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_download(String traceId,
                                          DownloadWaterRecordsRequest request,
                                          java.util.Map<String, String> __ctx,
                                          IceInternal.Functional_GenericCallback1<DownloadWaterRecordsResponse> __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                          IceInternal.Functional_BoolCallback __sentCb);

    public DownloadWaterRecordsResponse end_download(Ice.AsyncResult __result);
}
