// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `pc.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcPC;

public class QueryResponse extends PCBaseResponse
{
    public QueryResponse()
    {
        super();
        paymentVoucherNo = "";
        amount = "";
        channelCode = "";
        apiResultCode = "";
        extOrderNo = "";
        extWaterNo = "";
        ext1 = "";
        ext2 = "";
        ext3 = "";
        ext4 = "";
        ext5 = "";
    }

    public QueryResponse(String code, String paymentVoucherNo, String amount, String channelCode, String apiResultCode, String extOrderNo, String extWaterNo, String ext1, String ext2, String ext3, String ext4, String ext5)
    {
        super(code);
        this.paymentVoucherNo = paymentVoucherNo;
        this.amount = amount;
        this.channelCode = channelCode;
        this.apiResultCode = apiResultCode;
        this.extOrderNo = extOrderNo;
        this.extWaterNo = extWaterNo;
        this.ext1 = ext1;
        this.ext2 = ext2;
        this.ext3 = ext3;
        this.ext4 = ext4;
        this.ext5 = ext5;
    }

    private static class __F implements Ice.ObjectFactory
    {
        public Ice.Object create(String type)
        {
            assert(type.equals(ice_staticId()));
            return new QueryResponse();
        }

        public void destroy()
        {
        }
    }
    private static Ice.ObjectFactory _factory = new __F();

    public static Ice.ObjectFactory
    ice_factory()
    {
        return _factory;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::RpcPC::PCBaseResponse",
        "::RpcPC::QueryResponse"
    };

    public boolean ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[] ice_ids()
    {
        return __ids;
    }

    public String[] ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String ice_id()
    {
        return __ids[2];
    }

    public String ice_id(Ice.Current __current)
    {
        return __ids[2];
    }

    public static String ice_staticId()
    {
        return __ids[2];
    }

    protected void __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice(ice_staticId(), -1, false);
        __os.writeString(paymentVoucherNo);
        __os.writeString(amount);
        __os.writeString(channelCode);
        __os.writeString(apiResultCode);
        __os.writeString(extOrderNo);
        __os.writeString(extWaterNo);
        __os.writeString(ext1);
        __os.writeString(ext2);
        __os.writeString(ext3);
        __os.writeString(ext4);
        __os.writeString(ext5);
        __os.endWriteSlice();
        super.__writeImpl(__os);
    }

    protected void __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        paymentVoucherNo = __is.readString();
        amount = __is.readString();
        channelCode = __is.readString();
        apiResultCode = __is.readString();
        extOrderNo = __is.readString();
        extWaterNo = __is.readString();
        ext1 = __is.readString();
        ext2 = __is.readString();
        ext3 = __is.readString();
        ext4 = __is.readString();
        ext5 = __is.readString();
        __is.endReadSlice();
        super.__readImpl(__is);
    }

    public String paymentVoucherNo;

    public String amount;

    public String channelCode;

    public String apiResultCode;

    public String extOrderNo;

    public String extWaterNo;

    public String ext1;

    public String ext2;

    public String ext3;

    public String ext4;

    public String ext5;

    public QueryResponse
    clone()
    {
        return (QueryResponse)super.clone();
    }

    public static final long serialVersionUID = -7972033063473898516L;
}
